url: "Portfolio" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
collections:
  team:
    output: true
    permalink: /team/:path/
    
sass:
  style: compact # possible values: nested expanded compact compressed
